2024-03-02 19:22:11,760 ERROR: Exception on /dictionary/edit-term/5 [GET] [in C:\Users\Ayoub\Desktop\microblog\OAD-CP\.venv\Lib\site-packages\flask\app.py:828]
Traceback (most recent call last):
  File "C:\Users\Ayoub\Desktop\microblog\OAD-CP\.venv\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayoub\Desktop\microblog\OAD-CP\.venv\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayoub\Desktop\microblog\OAD-CP\.venv\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayoub\Desktop\microblog\OAD-CP\.venv\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayoub\Desktop\microblog\OAD-CP\app\dictionary\routes.py", line 99, in edit_term
    return render_template("dictionary/edit_term.html", term=term_to_edit)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayoub\Desktop\microblog\OAD-CP\.venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayoub\Desktop\microblog\OAD-CP\.venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayoub\Desktop\microblog\OAD-CP\.venv\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\Ayoub\Desktop\microblog\OAD-CP\.venv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Ayoub\Desktop\microblog\OAD-CP\app\templates\dictionary\edit_term.html", line 2, in top-level template code
    {% import "macros_wtf.html" as wtf %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayoub\Desktop\microblog\OAD-CP\app\templates\base.html", line 32, in top-level template code
    {% block content %}
  File "C:\Users\Ayoub\Desktop\microblog\OAD-CP\app\templates\dictionary\edit_term.html", line 18, in block 'content'
    {{ form.hidden_tag() }}
  File "C:\Users\Ayoub\Desktop\microblog\OAD-CP\.venv\Lib\site-packages\jinja2\environment.py", line 485, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'form' is undefined
2024-03-02 19:27:17,740 INFO: Decision Support Tool startup [in C:\Users\Ayoub\Desktop\microblog\OAD-CP\app\__init__.py:85]
2024-03-02 19:27:58,368 INFO: Decision Support Tool startup [in C:\Users\Ayoub\Desktop\microblog\OAD-CP\app\__init__.py:85]
2024-03-02 19:28:42,468 ERROR: Exception on /dictionary/edit-term/10 [GET] [in C:\Users\Ayoub\Desktop\microblog\OAD-CP\.venv\Lib\site-packages\flask\app.py:828]
Traceback (most recent call last):
  File "C:\Users\Ayoub\Desktop\microblog\OAD-CP\.venv\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayoub\Desktop\microblog\OAD-CP\.venv\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayoub\Desktop\microblog\OAD-CP\.venv\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayoub\Desktop\microblog\OAD-CP\.venv\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayoub\Desktop\microblog\OAD-CP\app\dictionary\routes.py", line 99, in edit_term
    return render_template("dictionary/edit_term.html", term=term_to_edit)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayoub\Desktop\microblog\OAD-CP\.venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayoub\Desktop\microblog\OAD-CP\.venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayoub\Desktop\microblog\OAD-CP\.venv\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\Ayoub\Desktop\microblog\OAD-CP\.venv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Ayoub\Desktop\microblog\OAD-CP\app\templates\dictionary\edit_term.html", line 2, in top-level template code
    {% import "macros_wtf.html" as wtf %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayoub\Desktop\microblog\OAD-CP\app\templates\base.html", line 32, in top-level template code
    {% block content %}
  File "C:\Users\Ayoub\Desktop\microblog\OAD-CP\app\templates\dictionary\edit_term.html", line 18, in block 'content'
    {{ form.hidden_tag() }}
  File "C:\Users\Ayoub\Desktop\microblog\OAD-CP\.venv\Lib\site-packages\jinja2\environment.py", line 485, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'form' is undefined
2024-03-02 19:28:48,154 ERROR: Exception on /dictionary/edit-term/10 [GET] [in C:\Users\Ayoub\Desktop\microblog\OAD-CP\.venv\Lib\site-packages\flask\app.py:828]
Traceback (most recent call last):
  File "C:\Users\Ayoub\Desktop\microblog\OAD-CP\.venv\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayoub\Desktop\microblog\OAD-CP\.venv\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayoub\Desktop\microblog\OAD-CP\.venv\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayoub\Desktop\microblog\OAD-CP\.venv\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayoub\Desktop\microblog\OAD-CP\app\dictionary\routes.py", line 99, in edit_term
    return render_template("dictionary/edit_term.html", term=term_to_edit)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayoub\Desktop\microblog\OAD-CP\.venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayoub\Desktop\microblog\OAD-CP\.venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayoub\Desktop\microblog\OAD-CP\.venv\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\Ayoub\Desktop\microblog\OAD-CP\.venv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Ayoub\Desktop\microblog\OAD-CP\app\templates\dictionary\edit_term.html", line 2, in top-level template code
    {% import "macros_wtf.html" as wtf %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayoub\Desktop\microblog\OAD-CP\app\templates\base.html", line 32, in top-level template code
    {% block content %}
  File "C:\Users\Ayoub\Desktop\microblog\OAD-CP\app\templates\dictionary\edit_term.html", line 18, in block 'content'
    {{ form.hidden_tag() }}
  File "C:\Users\Ayoub\Desktop\microblog\OAD-CP\.venv\Lib\site-packages\jinja2\environment.py", line 485, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'form' is undefined
2024-03-02 19:33:34,588 INFO: Decision Support Tool startup [in C:\Users\Ayoub\Desktop\microblog\OAD-CP\app\__init__.py:85]
2024-03-02 19:39:24,239 INFO: Decision Support Tool startup [in C:\Users\Ayoub\Desktop\microblog\OAD-CP\app\__init__.py:85]
2024-03-02 19:40:24,692 INFO: Decision Support Tool startup [in C:\Users\Ayoub\Desktop\microblog\OAD-CP\app\__init__.py:85]
2024-03-02 19:40:28,532 INFO: Decision Support Tool startup [in C:\Users\Ayoub\Desktop\microblog\OAD-CP\app\__init__.py:85]
2024-03-02 19:40:32,755 INFO: Decision Support Tool startup [in C:\Users\Ayoub\Desktop\microblog\OAD-CP\app\__init__.py:85]
2024-03-02 19:40:54,977 INFO: Decision Support Tool startup [in C:\Users\Ayoub\Desktop\microblog\OAD-CP\app\__init__.py:85]
2024-03-02 19:46:12,389 INFO: Decision Support Tool startup [in C:\Users\Ayoub\Desktop\microblog\OAD-CP\app\__init__.py:85]
2024-03-02 19:55:33,967 INFO: Decision Support Tool startup [in C:\Users\Ayoub\Desktop\microblog\OAD-CP\app\__init__.py:85]
